# Generated by Django 3.0.7 on 2020-06-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_districtp_duitama_southp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
    ]
