# Generated by Django 3.0.7 on 2020-06-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_districtp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
    ]
