# Generated by Django 3.0.7 on 2020-06-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_districtp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
    ]
