# Generated by Django 3.0.7 on 2020-06-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0020_districtp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
    ]
