# Generated by Django 3.0.7 on 2020-06-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0022_districtp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
        migrations.DeleteModel(
            name='Duitama_SouthP',
        ),
    ]
