# Generated by Django 3.0.7 on 2020-06-25 21:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0023_auto_20200625_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictP',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Duitama_Pump',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('area', models.FloatField()),
                ('clay', models.FloatField()),
                ('silt', models.FloatField()),
                ('sand', models.FloatField()),
                ('sp', models.FloatField()),
                ('fc', models.FloatField()),
                ('pwp', models.FloatField()),
                ('hc', models.FloatField()),
                ('density', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
