# Generated by Django 3.0.7 on 2020-06-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0024_districtp_duitama_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
        migrations.DeleteModel(
            name='Duitama_Pump',
        ),
    ]
