# Generated by Django 3.0.7 on 2020-07-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_cuche_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuche_Pump',
        ),
    ]
