# Generated by Django 3.0.7 on 2020-07-01 16:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0029_delete_cuche_pump'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuche_Pump',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('area', models.FloatField()),
                ('clay', models.FloatField()),
                ('silt', models.FloatField()),
                ('sand', models.FloatField()),
                ('sp', models.FloatField()),
                ('fc', models.FloatField()),
                ('pwp', models.FloatField()),
                ('hc', models.FloatField()),
                ('density', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Holanda_Pump',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=11)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('area', models.FloatField()),
                ('clay', models.FloatField()),
                ('silt', models.FloatField()),
                ('sand', models.FloatField()),
                ('sp', models.FloatField()),
                ('fc', models.FloatField()),
                ('pwp', models.FloatField()),
                ('hc', models.FloatField()),
                ('density', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
