# Generated by Django 3.0.7 on 2020-07-13 15:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0041_holanda_centroids_lasvueltas_centroids_ministerio_centroids_moniquira_centroids_pantanov_centroids_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='chicamocha_river',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('status', models.BigIntegerField()),
                ('length', models.FloatField()),
                ('flow', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
