# Generated by Django 3.0.7 on 2020-07-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0044_chicamocha_river'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chicamocha_river',
        ),
    ]
