# Generated by Django 3.0.7 on 2020-07-13 16:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0045_delete_chicamocha_river'),
    ]

    operations = [
        migrations.CreateModel(
            name='chicamocha_river',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('status', models.BigIntegerField()),
                ('length', models.FloatField()),
                ('flow', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
