# Generated by Django 3.0.7 on 2020-07-14 00:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0046_chicamocha_river'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservoirs',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('status', models.FloatField()),
                ('level', models.FloatField(null=True)),
                ('area', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
