# Generated by Django 3.0.7 on 2020-11-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0047_reservoirs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duitama_Pump',
        ),
    ]
