# Generated by Django 3.0.7 on 2020-11-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0049_duitama_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayalas_Pump',
        ),
    ]
