# Generated by Django 3.0.7 on 2020-11-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0051_ayalas_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuche_Pump',
        ),
    ]
