# Generated by Django 3.0.7 on 2020-11-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0053_cuche_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holanda_Pump',
        ),
    ]
