# Generated by Django 3.0.7 on 2020-11-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0055_holanda_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lasvueltas_Pump',
        ),
    ]
