# Generated by Django 3.0.7 on 2020-11-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0057_lasvueltas_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ministerio_Pump',
        ),
    ]
