# Generated by Django 3.0.7 on 2020-11-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0059_ministerio_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moniquira_Pump',
        ),
    ]
