# Generated by Django 3.0.7 on 2020-11-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0061_moniquira_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pantanov_pump',
        ),
    ]
