# Generated by Django 3.0.7 on 2020-11-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0063_pantanov_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sanrafael_pump',
        ),
    ]
