# Generated by Django 3.0.7 on 2020-11-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0065_sanrafael_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='surba_pump',
        ),
    ]
