# Generated by Django 3.0.7 on 2020-11-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0067_surba_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tibasosa_pump',
        ),
    ]
