# Generated by Django 3.0.7 on 2020-11-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0069_tibasosa_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ayalas_centroides',
        ),
    ]
