# Generated by Django 3.0.7 on 2020-11-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0071_ayalas_centroides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuche_centroides',
        ),
    ]
