# Generated by Django 3.0.7 on 2020-11-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0073_cuche_centroides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='duitama_centroides',
        ),
    ]
