# Generated by Django 3.0.7 on 2020-11-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0075_duitama_centroides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='holanda_centroids',
        ),
    ]
