# Generated by Django 3.0.7 on 2020-11-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0077_holanda_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lasvueltas_centroids',
        ),
    ]
