# Generated by Django 3.0.7 on 2020-11-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0079_lasvueltas_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ministerio_centroids',
        ),
    ]
