# Generated by Django 3.0.7 on 2020-11-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0081_ministerio_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moniquira_centroids',
        ),
    ]
