# Generated by Django 3.0.7 on 2020-11-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0083_moniquira_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pantanov_centroids',
        ),
    ]
