# Generated by Django 3.0.7 on 2020-11-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0085_pantanov_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sanrafael_centroids',
        ),
    ]
