# Generated by Django 3.0.7 on 2020-11-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0087_sanrafael_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='surba_centroids',
        ),
    ]
