# Generated by Django 3.0.7 on 2020-11-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0089_surba_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tibasosa_centroids',
        ),
    ]
