# Generated by Django 3.0.7 on 2020-12-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0091_tibasosa_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayalas_Pump',
        ),
    ]
