# Generated by Django 3.0.7 on 2020-12-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0095_ayalas_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayalas_Pump',
        ),
    ]
