# Generated by Django 3.0.7 on 2020-12-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0097_ayalas_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
    ]
