# Generated by Django 3.0.7 on 2020-12-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0101_districtp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
    ]
