# Generated by Django 3.0.7 on 2020-12-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0103_districtp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictP',
        ),
    ]
