# Generated by Django 3.0.7 on 2021-02-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0105_districtp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ayalas_centroides',
        ),
    ]
