# Generated by Django 3.0.7 on 2021-02-03 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0107_ayalas_centroides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ayalas_Pump',
        ),
    ]
