# Generated by Django 3.0.7 on 2021-02-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0111_cuche_centroides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuche_Pump',
        ),
    ]
