# Generated by Django 3.0.7 on 2021-02-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0112_delete_cuche_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuche_centroides',
        ),
    ]
