# Generated by Django 3.0.7 on 2021-02-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0114_cuche_centroides_cuche_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='duitama_centroides',
        ),
    ]
