# Generated by Django 3.0.7 on 2021-02-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0116_duitama_centroides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Duitama_Pump',
        ),
    ]
