# Generated by Django 3.0.7 on 2021-02-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0120_holanda_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holanda_Pump',
        ),
    ]
