# Generated by Django 3.0.7 on 2021-02-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0122_holanda_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lasvueltas_centroids',
        ),
    ]
