# Generated by Django 3.0.7 on 2021-02-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0124_lasvueltas_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lasvueltas_Pump',
        ),
    ]
