# Generated by Django 3.0.7 on 2021-02-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0126_lasvueltas_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ministerio_centroids',
        ),
    ]
