# Generated by Django 3.0.7 on 2021-02-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0128_ministerio_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ministerio_Pump',
        ),
    ]
