# Generated by Django 3.0.7 on 2021-02-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0130_ministerio_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moniquira_centroids',
        ),
    ]
