# Generated by Django 3.0.7 on 2021-02-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0132_moniquira_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moniquira_Pump',
        ),
    ]
