# Generated by Django 3.0.7 on 2021-02-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0134_moniquira_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pantanov_centroids',
        ),
    ]
