# Generated by Django 3.0.7 on 2021-02-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0136_pantanov_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pantanov_pump',
        ),
    ]
