# Generated by Django 3.0.7 on 2021-02-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0138_pantanov_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sanrafael_centroids',
        ),
    ]
