# Generated by Django 3.0.7 on 2021-02-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0140_sanrafael_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sanrafael_pump',
        ),
    ]
