# Generated by Django 3.0.7 on 2021-02-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0142_sanrafael_pump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='surba_centroids',
        ),
    ]
