# Generated by Django 3.0.7 on 2021-02-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0148_tibasosa_centroids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tibasosa_pump',
        ),
    ]
